In [65]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [67]:
iris=load_iris()

In [69]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [71]:
# Logistic Regression

In [73]:
scores_logistic=cross_val_score(LogisticRegression(max_iter=1000,solver='lbfgs'),iris.data,iris.target)
scores_logistic

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [75]:
np.average(scores_logistic)

0.9733333333333334

In [77]:
# Decision tree

In [79]:
scores_DecisionTree=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
scores_DecisionTree

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [81]:
np.average(scores_DecisionTree)

0.9666666666666668

In [83]:
# Random Forest

In [85]:
score_RandomForest = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
score_RandomForest

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [86]:
np.average(score_RandomForest)

0.9666666666666668

In [89]:
# Support Vector machine

In [91]:
source_svm=cross_val_score(SVC(),iris.data,iris.target)
source_svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [93]:
np.average(source_svm)

0.9666666666666666

In [ ]:
# For the given iris flower data we can see that Logistic Regression works well so far.